import logging
import time
from typing import List, Optional

from pydantic import ValidationError

from app.schemas import Plan, SectionDraft, Report, Fact, SectionResult, Issue
from app.agents.planner import plan
from app.agents.researcher import research
from app.agents.writer import write_section
from app.agents.revision import revise_until_approved
from app.llm import ask_json
from app.cache import cache_get, cache_set, is_cache_enabled, toggle_cache

logger = logging.getLogger(__name__)

# Disk cache root: <project_root>/.cache/
import os
CACHE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".cache")


def _run_with_retries(
    func,
    args: tuple = (),
    kwargs: dict = None,
    max_attempts: int = 3,
    backoff_seconds: int = 20,
    error_msg: str = "",
) -> Optional:
    """Run a function with retry logic for 429 rate-limit errors.

    For PER_DAY daily quota errors, stop immediately without retrying.
    All other 429 errors keep the 20-second retry, max 3 attempts.
    """
    if kwargs is None:
        kwargs = {}
    attempt = 0
    while attempt < max_attempts:
        try:
            result = func(*args, **kwargs)
            return result
        except Exception as e:
            err_str = str(e)
            # Check for daily quota exhaustion (PerDay in error text)
            if "PerDay" in err_str:
                logger.error(
                    "Daily free quota exhausted, retry later or switch model/provider. "
                    f"Error: {err_str}"
                )
                raise RuntimeError(
                    "Daily free quota exhausted, retry later or switch model/provider."
                ) from e
            # Check for rate-limit / 429 errors
            is_rate_limit = "429" in err_str or "rate" in err_str.lower() or "too many" in err_str.lower()
            attempt += 1
            if is_rate_limit and attempt < max_attempts:
                logger.warning(f"{error_msg} Attempt {attempt}/{max_attempts} failed with rate-limit error. Waiting {backoff_seconds}s...")
                time.sleep(backoff_seconds)
                continue
            else:
                logger.error(f"{error_msg} All {max_attempts} attempts failed. Last error: {err_str}")
                return None
    return None


def run_pipeline(
    topic: str,
    max_sections: Optional[int] = None,
    use_cache: bool = True,
) -> Optional[Report]:
    """Run the full research pipeline for a given topic.

    Steps:
        1. Plan: Break the topic into research sections.
        2. For each section: research the question, then use revise_until_approved
           to write and review the draft.
        3. Assemble the report with deduplicated source URLs and per-section pass/fail status.

    If planning fails or zero sections complete, returns None (caller should
    print error and exit with nonzero code).

    If daily quota is exhausted, raises RuntimeError.

    Each section is independently processed - if a section fails after max_rounds,
    it is marked as unverified (passed=False) but the pipeline continues with
    remaining sections.

    Args:
        topic: The research topic string.
        max_sections: Maximum number of sections to process (None = all).
        use_cache: Whether to use disk cache.

    Returns:
        A Report containing the topic, per-section SectionResult objects with
        draft/passed/issues/sources, and deduplicated source URLs,
        or None if the pipeline couldn't complete.
    """
    toggle_cache(use_cache)

    logger.info(f"Starting pipeline for topic: '{topic}'")
    start_time = time.time()

    # === Step 1: Plan ===
    logger.info("Step 1: Planning section breakdown...")
    plan_start = time.time()
    try:
        plan_result: Plan = plan(topic)
        plan_elapsed = time.time() - plan_start
        logger.info(f"Planning completed in {plan_elapsed:.2f}s: {len(plan_result.sections)} sections")
    except Exception as e:
        logger.error(f"Planning failed: {e}")
        return None

    if not plan_result.sections:
        logger.error("No sections generated by planner. Cannot continue.")
        return None

    # Apply max_sections limit if specified
    sections_to_process = plan_result.sections
    if max_sections is not None and isinstance(max_sections, int) and max_sections > 0:
        sections_to_process = sections_to_process[:max_sections]
        logger.info(f"Limited to {max_sections} sections (out of {len(plan_result.sections)} planned)")

    section_results: List[SectionResult] = []
    all_source_urls: set = set()

    # === Step 2: Research + Write+Review each section sequentially ===
    for i, section_plan in enumerate(sections_to_process, 1):
        section_num = i
        logger.info(f"Step 2.{section_num}: Researching section '{section_plan.title}'...")

        # Research the question for this section
        research_kwargs = {"question": section_plan.question}
        research_result = _run_with_retries(
            research,
            kwargs=research_kwargs,
            max_attempts=3,
            backoff_seconds=20,
            error_msg=f"Section {section_num} research",
        )

        if research_result is None or not research_result.facts:
            logger.warning(f"Section {section_num}: No facts retrieved, marking as unverified.")
            section_results.append(
                SectionResult(
                    draft=SectionDraft(
                        title=section_plan.title,
                        content="Not enough verified information found.",
                        source_urls=[],
                    ),
                    passed=False,
                    issues=[Issue(claim="", problem="no facts retrieved")],
                    sources=[],
                )
            )
            elapsed = time.time() - section_research_start if 'section_research_start' in dir() else 0
            logger.info(f"Section {section_num} research finished in {elapsed:.2f}s (no facts)")
            continue

        logger.info(
            f"Section {section_num} research finished in "
            f"{len(research_result.facts)} facts"
        )

        # Use revise_until_approved to write and review the draft
        logger.info(f"Section {section_num}: Starting write+review cycle...")
        revise_result = revise_until_approved(
            question=section_plan.question,
            facts=research_result.facts,
            max_rounds=3,
        )

        # Collect source URLs from the draft
        section_sources = revise_result["draft"].source_urls if revise_result["draft"] else []

        # Build the SectionResult
        section_result = SectionResult(
            draft=revise_result["draft"] if revise_result["draft"] else SectionDraft(
                title=section_plan.title,
                content="Not enough verified information found.",
                source_urls=[],
            ),
            passed=revise_result["passed"],
            issues=revise_result["issues"],
            sources=section_sources,
        )

        for url in section_sources:
            all_source_urls.add(url)

        section_results.append(section_result)
        logger.info(f"Section {section_num} completed: passed={revise_result['passed']}, issues={len(revise_result['issues'])}")

    # === Step 3: Assemble the report ===
    deduplicated_sources = list(all_source_urls)

    logger.info(f"Pipeline finished in {time.time() - start_time:.2f}s: {len(section_results)} sections, {len(deduplicated_sources)} deduplicated sources")

    report = Report(
        topic=topic,
        sections=section_results,
        sources=deduplicated_sources,
    )
    return report


def print_report(report: Report) -> None:
    """Print the report sections to console in a readable format."""
    print(f"\n=== Report: {report.topic} ===\n")
    passed_count = 0
    failed_count = 0
    for i, section in enumerate(report.sections, 1):
        status = "PASS" if section.passed else "FAIL"
        if section.passed:
            passed_count += 1
        else:
            failed_count += 1
        print(f"  {i}. {section.draft.title} [{status}]")
        print(f"     Content: {section.draft.content[:200]}{'...' if len(section.draft.content) > 200 else ''}")
        print(f"     Sources: {section.sources}")
        if section.issues:
            print(f"     Issues: {len(section.issues)} issue(s)")
            for issue in section.issues:
                print(f"       - '{issue.claim}': {issue.problem}")
    print(f"\n  Total sections: {len(report.sections)}")
    print(f"  Passed: {passed_count}, Failed: {failed_count}")
    print(f"  Total deduplicated sources: {len(report.sources)}")
    print(f"  Sources: {report.sources}\n")