import asyncio
import logging
import os
import re
import time
from typing import List, Optional, Callable

from pydantic import ValidationError

from app.schemas import Plan, SectionDraft, Report, Fact
from app.agents.planner import plan
from app.agents.researcher import research
from app.agents.writer import write_section
from app.llm import ask_json
from app.cache import cache_get, cache_set, is_cache_enabled, toggle_cache

logger = logging.getLogger(__name__)

# Disk cache root: <project_root>/.cache/
CACHE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".cache")


def _run_with_retries(
    func,
    args: tuple = (),
    kwargs: dict = None,
    max_attempts: int = 3,
    backoff_seconds: int = 20,
    error_msg: str = "",
) -> Optional:
    """Run a function with retry logic for 429 rate-limit errors.

    For PER_DAY daily quota errors, stop immediately without retrying.
    All other 429 errors keep the 20-second retry, max 3 attempts.
    """
    if kwargs is None:
        kwargs = {}
    attempt = 0
    while attempt < max_attempts:
        try:
            result = func(*args, **kwargs)
            return result
        except Exception as e:
            err_str = str(e)
            # Check for daily quota exhaustion (PerDay in error text)
            if "PerDay" in err_str:
                logger.error(
                    "Daily free quota exhausted, retry later or switch model/provider. "
                    f"Error: {err_str}"
                )
                raise RuntimeError(
                    "Daily free quota exhausted, retry later or switch model/provider."
                ) from e
            # Check for rate-limit / 429 errors
            is_rate_limit = "429" in err_str or "rate" in err_str.lower() or "too many" in err_str.lower()
            attempt += 1
            if is_rate_limit and attempt < max_attempts:
                logger.warning(f"{error_msg} Attempt {attempt}/{max_attempts} failed with rate-limit error. Waiting {backoff_seconds}s...")
                time.sleep(backoff_seconds)
                continue
            else:
                logger.error(f"{error_msg} All {max_attempts} attempts failed. Last error: {err_str}")
                return None
    return None


def run_pipeline(
    topic: str,
    max_sections: Optional[int] = None,
    use_cache: bool = True,
) -> Optional[Report]:
    """Run the full research pipeline for a given topic.

    Steps:
        1. Plan: Break the topic into research sections.
        2. For each section: research the question sequentially, then write the section.
        3. Assemble the report with deduplicated source URLs.

    If planning fails or zero sections complete, returns None (caller should
    print error and exit with nonzero code).

    If daily quota is exhausted, raises RuntimeError.

    Args:
        topic: The research topic string.
        max_sections: Maximum number of sections to process (None = all).
        use_cache: Whether to use disk cache.

    Returns:
        A Report containing the topic, list of drafted sections, and deduplicated
        source URLs, or None if the pipeline couldn't complete.
    """
    toggle_cache(use_cache)

    logger.info(f"Starting pipeline for topic: '{topic}'")
    start_time = time.time()

    # === Step 1: Plan ===
    logger.info("Step 1: Planning section breakdown...")
    plan_start = time.time()
    try:
        plan_result: Plan = plan(topic)
        plan_elapsed = time.time() - plan_start
        logger.info(f"Planning completed in {plan_elapsed:.2f}s: {len(plan_result.sections)} sections")
    except Exception as e:
        logger.error(f"Planning failed: {e}")
        return None

    if not plan_result.sections:
        logger.error("No sections generated by planner. Cannot continue.")
        return None

    # Apply max_sections limit if specified
    sections_to_process = plan_result.sections
    if max_sections is not None and isinstance(max_sections, int) and max_sections > 0:
        sections_to_process = sections_to_process[:max_sections]
        logger.info(f"Limited to {max_sections} sections (out of {len(plan_result.sections)} planned)")

    all_sections: List[SectionDraft] = []
    all_source_urls: set = set()

    # === Step 2: Research + Write each section sequentially ===
    for i, section_plan in enumerate(sections_to_process, 1):
        section_num = i
        logger.info(f"Step 2.{section_num}: Researching section '{section_plan.title}'...")
        section_research_start = time.time()

        # Use search_query directly from the section plan
        search_query = section_plan.search_query or section_plan.question
        logger.info(f"Section {section_num} search_query: '{search_query}'")

        # Research the question for this section
        research_kwargs = {"question": section_plan.question, "search_query": search_query}
        research_result = _run_with_retries(
            research,
            kwargs=research_kwargs,
            max_attempts=3,
            backoff_seconds=20,
            error_msg=f"Section {section_num} research",
        )

        if research_result is None or not research_result.facts:
            logger.warning(f"Section {section_num}: No facts retrieved, skipping write.")
            elapsed = time.time() - section_research_start
            logger.info(f"Section {section_num} research finished in {elapsed:.2f}s (no facts)")
            continue

        logger.info(
            f"Section {section_num} research finished in {time.time() - section_research_start:.2f}s: "
            f"{len(research_result.facts)} facts"
        )

        # Write the section from facts
        write_start = time.time()
        try:
            draft: SectionDraft = write_section(section_plan, research_result.facts)
        except RuntimeError as e:
            # If daily quota exhausted, stop the whole run immediately
            if "Daily free quota exhausted" in str(e):
                raise
            logger.error(f"Section {section_num} write failed: {e}")
            elapsed = time.time() - section_research_start
            logger.info(f"Section {section_num} finished in {elapsed:.2f}s (write error)")
            continue
        except Exception as e:
            logger.error(f"Section {section_num} write failed: {e}")
            elapsed = time.time() - section_research_start
            logger.info(f"Section {section_num} finished in {elapsed:.2f}s (write error)")
            continue

        write_elapsed = time.time() - write_start
        logger.info(
            f"Section {section_num} write finished in {write_elapsed:.2f}s: "
            f"'{draft.title}' with {len(draft.source_urls)} source URLs"
        )

        # Deduplicate source URLs
        for url in draft.source_urls:
            all_source_urls.add(url)

        all_sections.append(draft)
        logger.info(f"Section {section_num} completed.")

    # === Step 3: Check if any sections completed ===
    if not all_sections:
        logger.error("Zero sections completed. Cannot assemble a report.")
        return None

    total_elapsed = time.time() - start_time
    deduplicated_sources = list(all_source_urls)

    logger.info(f"Pipeline finished in {total_elapsed:.2f}s: {len(all_sections)} sections, {len(deduplicated_sources)} deduplicated sources")

    report = Report(
        topic=topic,
        sections=all_sections,
        sources=deduplicated_sources,
    )
    return report


def print_report(report: Report) -> None:
    """Print the report sections to console in a readable format."""
    print(f"\n=== Report: {report.topic} ===\n")
    for i, section in enumerate(report.sections, 1):
        print(f"  {i}. {section.title}")
        print(f"     Content: {section.content[:200]}{'...' if len(section.content) > 200 else ''}")
        print(f"     Sources: {section.source_urls}")
    print(f"\n  Total sections: {len(report.sections)}")
    print(f"  Total deduplicated sources: {len(report.sources)}")
    print(f"  Sources: {report.sources}\n")