import logging
import os

from app.schemas import Report

logger = logging.getLogger(__name__)


def _slugify(topic: str) -> str:
    """Convert a topic string to a filesystem-safe slug."""
    slug = "".join(
        character if character.isalnum() or character in "-_ " else ""
        for character in topic.strip()
    ).lower()
    return "-".join(slug.split())


def save_report(report: Report, output_dir: str = "reports") -> str:
    """Write a pipeline Report as Markdown and return its path."""
    os.makedirs(output_dir, exist_ok=True)

    source_urls = list(dict.fromkeys(
        report.sources
        + [url for section in report.sections for url in section.sources]
    ))
    source_numbers = {url: index for index, url in enumerate(source_urls, 1)}
    lines = [
        f"# {report.topic}",
        "",
        "> Generated by AI agents; verify sources",
        "",
    ]

    for section in report.sections:
        lines.extend([f"## {section.draft.title}", ""])
        if not section.passed:
            insufficient_evidence = any(
                issue.problem == "no facts retrieved" for issue in section.issues
            )
            notes = "; ".join(
                f"{issue.claim}: {issue.problem}".strip(": ")
                for issue in section.issues
            ) or "No review notes recorded."
            status = (
                "Insufficient evidence"
                if insufficient_evidence
                else "Unverified"
            )
            lines.extend([f"> **Status: {status}.** Review notes: {notes}", ""])
        citations = " ".join(
            f"[{source_numbers[url]}]"
            for url in dict.fromkeys(section.sources)
            if url in source_numbers
        )
        content = section.draft.content.rstrip()
        if citations:
            content = f"{content} {citations}"
        lines.extend([content, ""])

    lines.extend(["## Sources", ""])
    if source_urls:
        lines.extend(
            f"{index}. {url}" for index, url in enumerate(source_urls, 1)
        )
    else:
        lines.append("No sources.")

    filepath = os.path.join(output_dir, f"{_slugify(report.topic)}.md")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    logger.info("Generated Markdown report: %s", filepath)
    return filepath


generate_report = save_report


def print_report_summary(report: Report) -> None:
    """Print a quick summary of the report to console."""
    passed = sum(1 for s in report.sections if s.passed)
    insufficient = sum(
        1
        for section in report.sections
        if any(issue.problem == "no facts retrieved" for issue in section.issues)
    )
    failed = len(report.sections) - passed - insufficient
    print(f"\nReport: {report.topic}")
    print(
        f"  Sections: {len(report.sections)} (passed: {passed}, "
        f"failed reviews: {failed}, insufficient evidence: {insufficient})"
    )
    print(f"  Sources: {len(report.sources)}")