import os
import re
import time
from urllib.parse import urlparse

from app.schemas import Report, SectionDraft


def _slugify(topic: str) -> str:
    """Convert a topic string to a filesystem-safe slug."""
    slug = re.sub(r"[^\w\s-]", "", topic.strip())
    slug = re.sub(r"[\s]+", "-", slug)
    slug = slug.lower()
    return slug


def _format_citations(section: SectionDraft) -> str:
    """Format section content with inline [1], [2] citations based on source_urls."""
    citations = {}
    for i, url in enumerate(section.source_urls, 1):
        citations[i] = url
    # Simple inline citation replacement: number the source_urls in order
    content = section.content
    for num, url in citations.items():
        # Replace standalone number references with markdown citations
        content = content.replace(f" [{num}]", f" [{num}]({url})")
    return content


def save_report(report: Report) -> str:
    """Save a Report to disk as a markdown file.

    Creates the reports/ folder if needed.
    Writes: reports/<topic-slug>.md
    Returns the full path to the saved file.
    """
    # Ensure reports directory exists
    reports_dir = os.path.join(os.path.dirname(__file__), "..", "reports")
    os.makedirs(reports_dir, exist_ok=True)

    # Generate slug from topic
    slug = _slugify(report.topic)
    filepath = os.path.join(reports_dir, f"{slug}.md")

    # Build markdown content
    lines = []
    # Title
    lines.append(f"# {report.topic}")
    lines.append("")
    # Disclaimer
    lines.append("Generated by AI agents; verify sources.")
    lines.append("")
    # Sections
    for i, section in enumerate(report.sections, 1):
        lines.append(f"## {section.title}")
        # Format content with citations
        cit_content = _format_citations(section)
        lines.append(cit_content)
        lines.append("")
    # Sources list
    lines.append("## Sources")
    for i, url in enumerate(report.sources, 1):
        lines.append(f"[{i}]({url})")

    # Write file
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return filepath